[tool.poetry]
name = "dailywire-api"
version = "0.1.0"
description = "DailyWire API client and CLI"
authors = ["Samuël Visser <samuvisser@gmail.com>"]
packages = [{ include = "dailywire_api", from = "src" }]

[tool.poetry.dependencies]
python = "~3.13"
pydantic = "^2.11.7"

[tool.poetry.scripts]
dailywire-api = "dailywire_api.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
