### Authentication
# Define `access_token` in tests/rest/http-client.private.env.json. For example:
# {
#   "dev": {
#     "access_token": "<Daily Wire access token>"
#   }
# }

### Get episode details
@access_token = variable value
GET https://middleware-prod.dailywire.com/middleware/v4/getEpisode?slug=ep-2324-the-trump-administration-cracks-down-on-third-world-migration
Authorization: Bearer {{access_token}}


<> 2025-12-01T185815.200.json
<> 2025-12-01T185723.200.json
<> 2025-12-01T185607.200.json
<> 2025-12-01T184108.200.json
<> 2025-12-01T181114.200.json
<> 2025-12-01T181012.200.json
<> 2025-12-01T180946.200.json
<> 2025-12-01T180850.200.json
<> 2025-12-01T175757.200.json
<> 2025-12-01T175708.200.json
<> 2025-11-07T220712.200.json
<> 2025-11-07T191508.200.json
<> 2025-11-07T185915.200.json
<> 2025-11-07T183838.200.json
<> 2025-11-07T181122.200.json
<> 2025-11-07T175945.200.json
<> 2025-11-07T175531.200.json
<> 2025-11-07T175503.200.json

### Get movie details: Run Hide Fight
GET https://middleware-prod.dailywire.com/middleware/v4/getVideoPage?slug=run-hide-fight
Authorization: Bearer {{access_token}}


### Get movie details: Am I racist
GET https://middleware-prod.dailywire.com/middleware/v4/getVideoPage?slug=am-i-racist
Authorization: Bearer {{access_token}}


### Get movie details: Bonhoeffer
GET https://middleware-prod.dailywire.com/middleware/v4/getVideoPage?slug=bonhoeffer-pastor-spy-assassin
Authorization: Bearer {{access_token}}


### Get movie details
GET https://middleware-prod.dailywire.com/middleware/v4/getVideoPage?slug=hiding-in-plain-sight-america-s-trafficking-epidemic
Authorization: Bearer {{access_token}}

### Movie get video
GET https://middleware-prod.dailywire.com/middleware/v2/getVideo?slug=hiding-in-plain-sight-america-s-trafficking-epidemic
Authorization: Bearer {{access_token}}




### NextPage for new show results
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?
    lastPodcastEpisodeId=
    &lastShowEpisodeId=
    &membershipPlan=ALL_ACCESS
    &nextDate=&orderBy=published_at_desc
    &pageNumber=2
    &pageSize=10
    &podcastOffset=0
    &podcastSeasonId=
    &showOffset=10
    &showSeasonId=54e348fd-8560-4d9d-a5e0-dd6793cd8d05
    &slug=the-ben-shapiro-show"






### Get episodes for season 2026
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?lastPodcastEpisodeId=
    &lastShowEpisodeId=8232e42a-013c-43c9-be42-51e23d588ab9
    &membershipPlan=ALL_ACCESS
    &orderBy=CreatedAt_DESC
    &pageNumber=1
    &pageSize=6
    &podcastOffset=0
    &podcastSeasonId=
    &showOffset=0
    &showSeasonId=54e348fd-8560-4d9d-a5e0-dd6793cd8d05
    &slug=the-ben-shapiro-show
Authorization: Bearer {{access_token}}




### Get since 2024 later
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?showSeasonId=cmafuzh0ngcxl0738apl0yh08
    &membershipPlan=FREE
    &orderBy=CreatedAt_ASC
    &pageNumber=1
    &pageSize=50
    &showOffset=0
    &podcastOffset=1
    &slug=parenting
Authorization: Bearer {{access_token}}

<> 2025-10-25T191701.200.json
<> 2025-10-25T191618.200.json
<> 2025-10-25T191544.200.json
<> 2025-10-25T191500.200.json
<> 2025-10-25T144856.200.json
<> 2025-10-25T144314.200.json
<> 2025-10-25T144225.200.json
<> 2025-10-25T144139.200.json
<> 2025-10-25T144043.200.json
<> 2025-10-25T143737.200.json
<> 2025-10-25T143718.200.json
<> 2025-10-25T143700.200.json
<> 2025-10-25T143635.200.json
<> 2025-10-25T143346.500.json
<> 2025-10-25T143339.200.json

### Next?!
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?lastPodcastEpisodeId=
    &lastShowEpisodeId=cm2kl631co4pi0894ym7cjha5
    &membershipPlan=ALL_ACCESS
    &nextDate=2024-10-21
    &orderBy=CreatedAt_DESC
    &pageNumber=1
    &pageSize=50
    &podcastOffset=0
    &podcastSeasonId=
    &showOffset=100
    &showSeasonId=clqwfhdq3vpoo08345zkev0c0
    &slug=the-ben-shapiro-show

<> 2025-10-25T143444.200.json
<> 2025-10-25T143427.200.json
<> 2025-10-25T143317.200.json
<> 2025-10-25T143205.200.json





### GET User info
GET https://middleware-prod.dailywire.com/middleware/v3/getUserInfo?nocache=1
Authorization: Bearer {{access_token}}


### Get movie
GET https://middleware-prod.dailywire.com/middleware/v4/getVideoPage?slug=am-i-racist&membershipPlan=ALL_ACCESS
Authorization: Bearer {{access_token}}



<> 2025-10-30T214610.200.json
<> 2025-10-30T182038.200.json
<> 2025-10-30T174707.200.json
<> 2025-10-30T173239.200.json
<> 2025-10-30T173204.200.json

### TEst: pagination
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?membershipPlan=ALL_ACCESS&orderBy=CreatedAt_DESC&pageNumber=1&pageSize=50&podcastOffset=0&showOffset=0&showSeasonId=cmebjuclbtkv108220gr8hhkt&slug=the-isabel-brown-show
Authorization: Bearer {{access_token}}



#"/middleware/v4/getPaginatedEpisodes?lastPodcastEpisodeId=&lastShowEpisodeId=cmebjwwub38zu08501d1q9bo3&membershipPlan=ALL_ACCESS&nextDate=2025-08-13&orderBy=CreatedAt_DESC&pageNumber=2&pageSize=50&podcastOffset=0&podcastSeasonId=&showOffset=59&showSeasonId=cmebjuclbtkv108220gr8hhkt&slug=the-isabel-brown-show"




###
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?lastPodcastEpisodeId=&lastShowEpisodeId=cmebjwwub38zu08501d1q9bo3&membershipPlan=ALL_ACCESS&nextDate=2025-08-13&orderBy=CreatedAt_DESC&pageNumber=2&pageSize=50&podcastOffset=0&podcastSeasonId=&showOffset=59&showSeasonId=cmebjuclbtkv108220gr8hhkt&slug=the-isabel-brown-show
Authorization: Bearer {{access_token}}


###
GET https://middleware-prod.dailywire.com//middleware/v4/getPaginatedEpisodes?lastPodcastEpisodeId=&lastShowEpisodeId=cmebjwwub38zu08501d1q9bo3&membershipPlan=ALL_ACCESS&nextDate=2025-08-13&orderBy=CreatedAt_DESC&pageNumber=3&pageSize=50&podcastOffset=0&podcastSeasonId=&showOffset=60&showSeasonId=cmebjuclbtkv108220gr8hhkt&slug=the-isabel-brown-show


### Get episode details
GET https://middleware-prod.dailywire.com/middleware/v4/getEpisode?slug=ep-2324-the-trump-administration-cracks-down-on-third-world-migration
Authorization: Bearer {{access_token}}

<> 2025-12-01T175614.200.json


### Get episode details
GET https://middleware-prod.dailywire.com/middleware/v4/getNextEpisode?direction=NEXT&episodeId=ck1x83ea9zq8p0722546dfl2y&membershipPlan=ALL_ACCESS&showId=ck0gx918z008007947vwinup8&type=SHOW
Authorization: Bearer {{access_token}}

### Get watch page
GET https://middleware-prod.dailywire.com/middleware/v4/getPage?slug=watch-page&membershipPlan=ALL_ACCESS
Authorization: Bearer {{access_token}}

### GET the Ben Shapiro Show
GET https://middleware-prod.dailywire.com/middleware/v4/getShowPage?slug=the-ben-shapiro-show&membershipPlan=ALL_ACCESS
Authorization: Bearer {{access_token}}


<> 2025-12-01T175501.200.json
<> 2025-12-01T175449.200.json
<> 2025-11-04T211653.200.json
<> 2025-10-25T151607.200.json
<> 2025-09-25T004941.200.json
<> 2025-09-15T174320.200.json
<> 2025-09-12T110601.200.json
<> 2025-09-12T103447.200.json

### GET non- existing show
GET https://middleware-prod.dailywire.com/middleware/v4/getShowPage?slug=the-ben-shapiro-sho

<> 2025-09-12T110635.500.txt
<> 2025-09-12T110603.500.txt
<> 2025-09-12T103514.500.txt

### Get episodes. Statusses: LIVE, PUBLISHED (between: processing: video is not available at all, post-processing: video is available, but still contains the waiting timer before the stream)
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?membershipPlan=ALL_ACCESS&orderBy=CreatedAt_DESC&pageNumber=1&pageSize=11&podcastOffset=0&showOffset=0&showSeasonId=cm5fobybv7zsu08144t60uf3y&slug=the-ben-shapiro-show
Authorization: Bearer {{access_token}}



###
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?slug=the-ben-shapiro-show&orderBy=pishedAt_DESC&pageNumber=1&pageSize=50&showOffset=0&podcastOffset=0&showSeasonId=cm5fobybv7zsu08144t60uf3y

###
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?lastShowEpisodeId=cm6jh04th183v0814b51f9tiw&membershipPlan=FREE&nextDate=2025-01-29&orderBy=CreatedAt_DESC&pageNumber=5&pageSize=50&podcastOffset=0&showOffset=397&showSeasonId=cm5fobybv7zsu08144t60uf3y&slug=the-ben-shapiro-show

###

<> 2025-10-23T202932.200.json


### Directly from next page in Show
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes?lastPodcastEpisodeId=&lastShowEpisodeId=cmg6nka6bda2z0994syrr88jb&membershipPlan=FREE&nextDate=2025-09-30&orderBy=CreatedAt_DESC&pageNumber=2&pageSize=11&podcastOffset=0&podcastSeasonId=&showOffset=20&showSeasonId=cm5fobybv7zsu08144t60uf3y&slug=the-ben-shapiro-show"


###################################################################
# DEBUG: Missing latest episodes investigation (2026-04-13)
###################################################################

### TEST 1: getShowPage - Check current seasons & latest_season ID
# Compare returned episodes with getPaginatedEpisodes results
GET https://middleware-prod.dailywire.com/middleware/v4/getShowPage
    ?slug=the-ben-shapiro-show
    &membershipPlan=ALL_ACCESS
Authorization: Bearer {{access_token}}


### TEST 2: Clean first page - NO cursor, offset=0, new season ID
# This should return the very latest episodes without stale cursor interference
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?slug=the-ben-shapiro-show
    &membershipPlan=ALL_ACCESS
    &orderBy=CreatedAt_DESC
    &pageNumber=1
    &pageSize=20
    &showOffset=0
    &podcastOffset=0
    &showSeasonId=54e348fd-8560-4d9d-a5e0-dd6793cd8d05
Authorization: Bearer {{access_token}}


### TEST 3: No season ID at all - does the API default to latest season?
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?slug=the-ben-shapiro-show
    &membershipPlan=ALL_ACCESS
    &orderBy=CreatedAt_DESC
    &pageNumber=1
    &pageSize=20
    &showOffset=0
    &podcastOffset=0
Authorization: Bearer {{access_token}}


### TEST 4: Try published_at ordering instead of CreatedAt
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?slug=the-ben-shapiro-show
    &membershipPlan=ALL_ACCESS
    &orderBy=published_at_desc
    &pageNumber=1
    &pageSize=20
    &showOffset=0
    &podcastOffset=0
    &showSeasonId=54e348fd-8560-4d9d-a5e0-dd6793cd8d05
Authorization: Bearer {{access_token}}


### TEST 5: Old season ID (cmju9xb4z36ro0862o9uu36gq) clean - compare results
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?slug=the-ben-shapiro-show
    &membershipPlan=ALL_ACCESS
    &orderBy=CreatedAt_DESC
    &pageNumber=1
    &pageSize=20
    &showOffset=0
    &podcastOffset=0
    &showSeasonId=cmju9xb4z36ro0862o9uu36gq
Authorization: Bearer {{access_token}}


### TEST 6: Minimal query - just slug, season, and ordering
GET https://middleware-prod.dailywire.com/middleware/v4/getPaginatedEpisodes
    ?slug=the-ben-shapiro-show
    &showSeasonId=54e348fd-8560-4d9d-a5e0-dd6793cd8d05
    &orderBy=CreatedAt_DESC
    &pageSize=50
    &showOffset=0
    &podcastOffset=0
Authorization: Bearer {{access_token}}
