[project]
name = "task-manager"
version = "0.1.0"
description = "Task scheduling and event management system for WireLoft."
authors = [{ name = "Samuël Visser", email = "samuvisser@gmail.com" }]
requires-python = ">=3.13,<3.14"
dependencies = [
  "APScheduler>=3.11.0,<4.0",
  "pyventus>=0.7.2",
  "SQLAlchemy>=2.0.43,<3.0",
  "backend",
  "dailywire-api"
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
backend = { workspace = true }
dailywire-api = { workspace = true }