[project]
name = "wireloft-controller"
version = "0.1.0"
description = "Task controller and definitions for WireLoft"
authors = [{ name = "Samuël Visser", email = "samuvisser@gmail.com" }]
requires-python = ">=3.13,<3.14"
dependencies = [
  "requests>=2.32.3,<3.0",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
